apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: models-web-app
        image: 768556645518.dkr.ecr.ap-northeast-1.amazonaws.com/data-kubeflow:model-v0.0.4
        ports:
        - containerPort: 5000
        env:
        - name: APP_PREFIX
          value: $(VWA_PREFIX)
        - name: USERID_HEADER
          value: $(VWA_USERID_HEADER)
        - name: USERID_PREFIX
          value: $(VWA_USERID_PREFIX)
      serviceAccountName: service-account
