apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
namePrefix: models-web-app-
namespace: kubeflow
commonLabels:
  app: models-web-app
  kustomize.component: models-web-app
images:
- name: 768556645518.dkr.ecr.ap-northeast-1.amazonaws.com/data-kubeflow:model-v0.0.4
  newName: 768556645518.dkr.ecr.ap-northeast-1.amazonaws.com/data-kubeflow
  newTag: model-v0.0.4
# We need the name to be unique without the suffix because the original name is what
# gets used with patches
configMapGenerator:
- envs:
  - params.env
  name: parameters
vars:
- fieldref:
    fieldPath: data.VWA_CLUSTER_DOMAIN
  name: VWA_CLUSTER_DOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: metadata.namespace
  name: VWA_NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: service
- fieldref:
    fieldPath: data.VWA_USERID_HEADER
  name: VWA_USERID_HEADER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.VWA_USERID_PREFIX
  name: VWA_USERID_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.VWA_PREFIX
  name: VWA_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
